name: Instagram Scraper

on:
  workflow_dispatch:
    inputs:
      profile_url:
        description: 'Instagram Profile URL or username'
        required: true
      start_date:
        description: 'Start Date (YYYY-MM-DD)'
        required: true
      end_date:
        description: 'End Date (YYYY-MM-DD)'
        required: true
      username:
        description: 'Instagram Username'
        required: true
      artifact_name:
        description: 'Unique artifact name to store CSV'
        required: true

jobs:
  scrape:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # ------------------------------
    # Set up Python
    # ------------------------------
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # ------------------------------
    # 🟢 Cache pip dependencies (Windows path)
    # ------------------------------
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: C:\Users\runneradmin\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # ------------------------------
    # Install dependencies
    # ------------------------------
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # ------------------------------
    # Run scraper
    # ------------------------------
    - name: Run scraper
      run: python scraper.py "${{ github.event.inputs.profile_url }}" "${{ github.event.inputs.start_date }}" "${{ github.event.inputs.end_date }}" "${{ github.event.inputs.username }}" "${{ github.event.inputs.artifact_name }}"

    # ------------------------------
    # Upload scraped CSV
    # ------------------------------
    - name: Upload scraped CSV as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.artifact_name }}
        path: "*.csv"

    # ------------------------------
    # Upload first screenshot if any
    # ------------------------------
    - name: Upload screenshot artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: click-error-screenshot
        path: click_error.png

    # ------------------------------
    # Upload second screenshot if any
    # ------------------------------
    - name: Upload second screenshot artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: click-error-screenshot-1
        path: click_error1.png
